#ifndef SOMIGAME_HEAD_DEFS_HXX
#define SOMIGAME_HEAD_DEFS_HXX

#ifndef SOMIGAME_NAME
#   define SOMIGAME_NAME somigame
#endif//SOMIGAME_NAME
#ifndef SOMIGAME_NAME_STR
#   define SOMIGAME_NAME_STR #SOMIGAME_NAME
#endif//SOMIGAME_NAME_STR

#ifndef SOMIGAME_VNUM
#   define SOMIGAME_VNUM 0xa0a3a0
#endif//SOMIGAME_VNUM
#ifndef SOMIGAME_VNUM_STR
#   define SOMIGAME_VNUM_STR #SOMIGAME_VNUM
#endif//SOMIGAME_VNUM_STR

#define _DECL_DATA extern
#define _DEFN_DATA
#define _DECL_FUNC extern
#define _DEFN_FUNC

#endif//SOMIGAME_HEAD_DEFS_HXX
